### ISSUE TITLE
Performance claims

### ISSUE THREAD

**Issue by jakoss** [linhnvtit/quick-image#1]
> This library loads images with considerably higher speed and lower resource consumption compared to others

This is one bold claim, do you have any measurements to support that? Considering another library when we have multiplatform library like coil is a huge investment. You need something to back up your claims here

**Comment by linhnvtit** [comment]
Thank you for bringing this to my attention. I apologize for the inadvertent inclusion of the phrase in the README. This was an unintentional error on my part.

I have corrected the README and removed the phrase. Thanks.
